import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';

const sandbox = { window: {} };
vm.runInNewContext(readFileSync(new URL('../assets/js/seed-sidequests.js', import.meta.url), 'utf8'), sandbox);
assert.equal(sandbox.window.GAME_SIDEQUESTS.routes.length, 3, '编辑器需保存三条支线路线');
assert.equal(sandbox.window.GAME_SIDEQUEST_TALENTS.length, 12, '编辑器需同步 12 枚限定文心');
assert.deepEqual([...sandbox.window.GAME_SIDEQUEST_TALENTS.map(t => t.id)].sort(), ['T041','T042','T043','T044','T045','T046','T047','T048','T049','TA09','TA10','TA11'].sort());
const npcRoutes = Object.values(sandbox.window.GAME_SIDEQUEST_NPCS.routes);
const npcIds = npcRoutes.flatMap(route => [route.guides[0], route.climax, ...Object.values(route.final.secondary)]).map(npc => npc.id);
assert.equal(new Set(npcIds).size, 9, '编辑器需同步剩余 9 名支线专属 NPC');
const common = readFileSync(new URL('../assets/js/common.js', import.meta.url), 'utf8');
const npcEditor = readFileSync(new URL('../assets/js/npc.js', import.meta.url), 'utf8');
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
assert.match(common, /project\.sidequests = global\.GAME_SIDEQUESTS/, '导出工程必须携带支线 NPC 与路线');
assert.match(common, /NPC\.exportSideQuestRaw/, '工程导出必须读取编辑器当前的支线 NPC 数据');
assert.match(common, /NPC\.importSideQuestNpcs/, '工程/云端导入必须回写编辑器当前的支线 NPC 数据');
assert.match(npcEditor, /function renderSideQuestNpcList\(/, 'NPC 编辑器必须渲染专属角色列表');
assert.match(npcEditor, /exportSideQuestRaw, importSideQuestNpcs/, 'NPC 编辑器必须公开专属角色的导入导出接口');
assert.match(html, /id="sidequestNpcList"/, 'NPC 页面必须存在支线专属 NPC 可见列表');
assert.match(html, /id="sidequestNpcJson"/, 'NPC 页面必须提供专属角色配置编辑入口');
console.log('sidequest-content-sync.test.mjs: 编辑器支线内容同步 ✓');
